site_name: rwny
site_url: https://rwny.github.io/b3d-classroom  # update with your GitHub username/repo
theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Noto Sans Thai Looped
    code: Roboto Mono
  features:
    - navigation.instant
  icon:
    logo: material/book-open-page-variant
nav:
  - Home: index.md
  - Vector:
      - vector: Vector/vector.md
  - Mesh: 
      - box: Mesh/box.md
      - cube: Mesh/cube.md
plugins:
  - search
extra_css:
  - stylesheets/extra.css